#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jul 21 17:55:13 2025

@author: dexter
"""

from ..WebAPI.trade_routing_2_pb2 import TradeSubscription as TS
from ..WebAPI.order_2_pb2 import Order as Ord #Side, OrderType, Duration

SUBSCRIPTION_SCOPE_ORDERS = TS.SubscriptionScope.SUBSCRIPTION_SCOPE_ORDERS
SUBSCRIPTION_SCOPE_POSITIONS = TS.SubscriptionScope.SUBSCRIPTION_SCOPE_POSITIONS
SUBSCRIPTION_SCOPE_COLLATERAL = TS.SubscriptionScope.SUBSCRIPTION_SCOPE_COLLATERAL
SUBSCRIPTION_SCOPE_ACCOUNT_SUMMARY = TS.SubscriptionScope.SUBSCRIPTION_SCOPE_ACCOUNT_SUMMARY
SUBSCRIPTION_SCOPE_EXCHANGE_POSITIONS = TS.SubscriptionScope.SUBSCRIPTION_SCOPE_EXCHANGE_POSITIONS
SUBSCRIPTION_SCOPE_EXCHANGE_BALANCES = TS.SubscriptionScope.SUBSCRIPTION_SCOPE_EXCHANGE_BALANCES

SIDE_BUY = Ord.Side.SIDE_BUY
SIDE_SELL = Ord.Side.SIDE_SELL

ORDER_TYPE_MKT = Ord.OrderType.ORDER_TYPE_MKT
ORDER_TYPE_LMT = Ord.OrderType.ORDER_TYPE_LMT
ORDER_TYPE_STP = Ord.OrderType.ORDER_TYPE_STP
ORDER_TYPE_STL = Ord.OrderType.ORDER_TYPE_STL
ORDER_TYPE_CROSS = Ord.OrderType.ORDER_TYPE_CROSS

DURATION_DAY = Ord.Duration.DURATION_DAY
DURATION_GTC = Ord.Duration.DURATION_GTC
DURATION_GTD = Ord.Duration.DURATION_GTD
DURATION_GTT = Ord.Duration.DURATION_GTT
DURATION_FOK = Ord.Duration.DURATION_FOK
DURATION_FAK = Ord.Duration.DURATION_FAK
DURATION_FOK = Ord.Duration.DURATION_FOK
DURATION_ATO = Ord.Duration.DURATION_ATO
DURATION_ATC = Ord.Duration.DURATION_ATC
DURATION_GFA = Ord.Duration.DURATION_GFA