
class EC_APIError(Exception):
    """Base case for EC_API Error"""

class ConnectError(EC_APIError):...
class DisconnectError(EC_APIError):...

class AuthError(EC_APIError):...

class RoutingError(EC_APIError):...
class UnknownRouterKeyError(EC_APIError):...

class MaxSymbolsExceeded(EC_APIError):...
class MaxSubscribersExceeded(EC_APIError):...
